//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApp.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVIDAD()
        {
            this.CALIFICACION = new HashSet<CALIFICACION>();
            this.VALORACION = new HashSet<VALORACION>();
            this.DETALLE_ACTIVIDAD = new HashSet<DETALLE_ACTIVIDAD>();
        }
    
        public int ID_ACTIVIDAD { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public string IMAGEN { get; set; }
        public byte[] ARCHIVO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_LIMITE { get; set; }
        public int ESTADO { get; set; }
        public int ID_CUESTIONARIO { get; set; }
        public int ACTIVIDAD_TIPO { get; set; }
        public int ID_COMPETENCIA { get; set; }
        public int ID_CURSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALIFICACION> CALIFICACION { get; set; }
        public virtual TIPO_ACTIVIDAD TIPO_ACTIVIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALORACION> VALORACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ACTIVIDAD> DETALLE_ACTIVIDAD { get; set; }
        public virtual COMPETENCIA COMPETENCIA { get; set; }
        public virtual CUESTIONARIO CUESTIONARIO { get; set; }
        public virtual CURSOS CURSOS { get; set; }
    }
}
