//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApp.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACIDADES
    {
        public int ID_CAPACIDAD { get; set; }
        public int ID_COMPETENCIA { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual COMPETENCIA COMPETENCIA { get; set; }
    }
}
