//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApp.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPETENCIA()
        {
            this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
        }
    
        public int ID_COMPETENCIA { get; set; }
        public string NOMBRE { get; set; }
        public string DETALLE { get; set; }
        public string PROGRESO { get; set; }
        public int ID_CURSO { get; set; }
        public int ID_TIPO_COMPETENCIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual CURSOS CURSOS { get; set; }
        public virtual TIPO_COMPETENCIA TIPO_COMPETENCIA { get; set; }
    }
}
