//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApp.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETENCIA_SECCION
    {
        public int ID_COMPETENCIASECCION { get; set; }
        public int ID_CURSO { get; set; }
        public int ID_DOCENTE { get; set; }
        public string PROGRESO { get; set; }
        public int ID_COMPETENCIA { get; set; }
    
        public virtual COMPETENCIA COMPETENCIA { get; set; }
        public virtual CURSOS CURSOS { get; set; }
        public virtual DOCENTE DOCENTE { get; set; }
    }
}
