//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApp.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURSOS()
        {
            this.COMPETENCIA = new HashSet<COMPETENCIA>();
            this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
        }
    
        public int ID_CURSO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public int HORAS { get; set; }
        public string NIVEL { get; set; }
        public int ESTADO { get; set; }
        public string IMAGEN { get; set; }
        public int GRADO_SECCION_CURSO { get; set; }
        public int ID_DOCENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETENCIA> COMPETENCIA { get; set; }
        public virtual GRADO_SECCION GRADO_SECCION { get; set; }
        public virtual DOCENTE DOCENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
    }
}
